import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { corsHeaders } from '../_shared/cors.ts';

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const bookingData = await req.json();
    console.log('Received booking data:', JSON.stringify(bookingData, null, 2));

    const {
      tour_id,
      date_slot_id,
      hiker_id,
      participants,
      participants_details,
      total_price,
      subtotal,
      discount_code,
      discount_amount,
      service_fee_amount,
      currency,
      special_requests,
      stripe_payment_intent_id,
      primary_contact_id,
      payment_type,
      payment_status,
      deposit_amount,
      final_payment_amount,
      final_payment_due_date,
      final_payment_status,
    } = bookingData;

    console.log('Validating required fields...');
    console.log('Field values:', {
      tour_id,
      date_slot_id,
      hiker_id,
      participants,
      total_price,
      subtotal,
      currency
    });
    
    if (!tour_id || !date_slot_id || !hiker_id || !participants || !total_price) {
      console.error('Missing required fields:', {
        tour_id: !!tour_id,
        date_slot_id: !!date_slot_id,
        hiker_id: !!hiker_id,
        participants: !!participants,
        total_price: !!total_price
      });
      return new Response(
        JSON.stringify({ error: 'Missing required booking information' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log('All required fields present, proceeding with booking creation...');

    // Create Supabase client
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Get tour info and check auto_confirm setting
    console.log('Fetching tour info for tour_id:', tour_id);
    const { data: tour, error: tourError } = await supabase
      .from('tours')
      .select('title, guide_id, auto_confirm, region, meeting_point')
      .eq('id', tour_id)
      .maybeSingle();

    if (tourError) {
      console.error('Tour fetch error:', tourError);
      return new Response(
        JSON.stringify({ error: 'Failed to fetch tour', details: tourError }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }
    
    if (!tour) {
      console.error('Tour not found for id:', tour_id);
      return new Response(
        JSON.stringify({ error: 'Tour not found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }
    console.log('Tour found:', tour.title);

    // Get date slot info
    console.log('Fetching date slot info for date_slot_id:', date_slot_id);
    const { data: dateSlot, error: dateSlotError } = await supabase
      .from('tour_date_slots')
      .select('slot_date, spots_booked, spots_total')
      .eq('id', date_slot_id)
      .maybeSingle();

    if (dateSlotError) {
      console.error('Date slot fetch error:', dateSlotError);
      return new Response(
        JSON.stringify({ error: 'Failed to fetch date slot', details: dateSlotError }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }
    
    if (!dateSlot) {
      console.error('Date slot not found for id:', date_slot_id);
      return new Response(
        JSON.stringify({ error: 'Date slot not found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }
    
    // Calculate spots remaining
    const spotsRemaining = dateSlot.spots_total - dateSlot.spots_booked;
    console.log('Date slot found:', { ...dateSlot, spotsRemaining });

    // Check if enough spots are available
    if (spotsRemaining < participants) {
      console.error('Not enough spots:', { spotsRemaining, requestedParticipants: participants });
      return new Response(
        JSON.stringify({ error: 'Not enough spots available' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Determine booking status based on auto_confirm setting
    const bookingStatus = tour.auto_confirm ? 'confirmed' : 'pending_confirmation';

    // Create booking record (booking_reference will be auto-generated by trigger)
    console.log('Creating booking with data:', {
      tour_id,
      date_slot_id,
      hiker_id,
      booking_date: dateSlot.slot_date,
      participants,
      status: bookingStatus,
      payment_status: payment_status || 'succeeded',
      payment_type,
      deposit_amount,
      final_payment_amount,
      final_payment_status
    });
    const { data: booking, error: bookingError } = await supabase
      .from('bookings')
      .insert({
        tour_id,
        date_slot_id,
        hiker_id,
        booking_date: dateSlot.slot_date,
        participants,
        participants_details,
        total_price,
        subtotal,
        discount_code,
        discount_amount: discount_amount || 0,
        service_fee_amount: service_fee_amount || 0,
        currency,
        status: bookingStatus,
        payment_status: payment_status || 'succeeded',
        special_requests,
        stripe_payment_intent_id,
        primary_contact_id,
        payment_type: payment_type || 'full',
        deposit_amount: deposit_amount || null,
        final_payment_amount: final_payment_amount || null,
        final_payment_due_date: final_payment_due_date || null,
        final_payment_status: final_payment_status || null,
      })
      .select()
      .single();

    if (bookingError) {
      console.error('Error creating booking:', bookingError);
      return new Response(
        JSON.stringify({ error: 'Failed to create booking', details: bookingError }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }
    console.log('Booking created successfully:', booking.id, 'Reference:', booking.booking_reference);

    // Update tour_date_slots to reflect booked spots
    const newSpotsBooked = dateSlot.spots_booked + participants;
    const { error: updateSlotsError } = await supabase
      .from('tour_date_slots')
      .update({
        spots_booked: newSpotsBooked,
      })
      .eq('id', date_slot_id);

    if (updateSlotsError) {
      console.error('Error updating slots:', updateSlotsError);
    }

    // Increment discount code usage if applicable
    if (discount_code) {
      const { data: currentCode } = await supabase
        .from('discount_codes')
        .select('times_used')
        .eq('code', discount_code)
        .single();
      
      if (currentCode) {
        await supabase
          .from('discount_codes')
          .update({ times_used: currentCode.times_used + 1 })
          .eq('code', discount_code);
      }
    }

    // Create conversation between hiker and guide
    const { data: conversation, error: conversationError } = await supabase
      .from('conversations')
      .insert({
        hiker_id: hiker_id,
        guide_id: tour.guide_id,
        tour_id: tour_id,
        last_message_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (conversationError) {
      console.error('Error creating conversation:', conversationError);
    }

    // Send confirmation email to hiker
    console.log('Sending confirmation email to hiker...');
    try {
      const { data: hikerProfile } = await supabase
        .from('profiles')
        .select('email, name')
        .eq('id', hiker_id)
        .single();

      const { data: guideProfile } = await supabase
        .from('guide_profiles')
        .select('display_name')
        .eq('user_id', tour.guide_id)
        .single();

      if (hikerProfile?.email) {
        await supabase.functions.invoke('send-email', {
          body: {
            type: 'booking-confirmation',
            to: hikerProfile.email,
            bookingReference: booking.booking_reference,
            tourTitle: tour.title,
            bookingDate: booking.booking_date,
            guideName: guideProfile?.display_name || 'Your Guide',
            meetingPoint: tour.meeting_point || 'Details will be shared',
            totalPrice: total_price,
            currency: currency,
            participants: participants,
            isDeposit: payment_type === 'deposit',
            depositAmount: deposit_amount || undefined,
            finalPaymentAmount: final_payment_amount || undefined,
            finalPaymentDueDate: final_payment_due_date || undefined,
          }
        });
        console.log('Confirmation email sent successfully');
      }
    } catch (emailError) {
      console.error('Error sending confirmation email:', emailError);
      // Don't fail the booking if email fails
    }

    console.log('Booking created successfully:', booking.id);

    return new Response(
      JSON.stringify({
        booking,
        conversation,
        message: 'Booking created successfully'
      }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in create-booking:', error);
    return new Response(
      JSON.stringify({ error: 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
