-- Complete migration Part 3: Final regions (Spain, Sweden, Switzerland, Turkey, UK)

INSERT INTO hiking_regions (country, region, subregion, description, key_features, is_active) VALUES
-- Spain (29 regions) - Lines 300-328
('Spain', 'Pyrenees', 'Ordesa y Monte Perdido National Park', 'Spanish Pyrenees gem', ARRAY['Ordesa Canyon', 'Monte Perdido (3355m)', 'Cola de Caballo', 'UNESCO'], true),
('Spain', 'Pyrenees', 'Añisclo Escuaín & Pineta Canyons', 'Dramatic gorges and cirques', ARRAY['Ibex habitat', 'Glacial cirques', 'Canyons', 'Wild'], true),
('Spain', 'Pyrenees', 'Aigüestortes i Estany de Sant Maurici', '200+ lakes in Catalan Pyrenees', ARRAY['Twisted Waters', 'Els Encantats', 'Carros de Foc', 'Alpine'], true),
('Spain', 'Pyrenees', 'Pic de Ratera Circuit', 'Lake views circuit', ARRAY['Carros de Foc 7-day', 'Huts', 'Circuit', 'Alpine'], true),
('Spain', 'Pyrenees', 'Vall d''Aran', 'Northern valley with different climate', ARRAY['Aneto approach (3404m)', 'Microclimate', 'Catalan', 'Highest Pyrenees'], true),
('Spain', 'Pyrenees', 'GR11', '820km coast-to-coast Spanish Pyrenees', ARRAY['Atlantic to Mediterranean', 'Spanish side', 'Multi-week', 'Epic'], true),
('Spain', 'Picos de Europa', 'Cares Gorge (Garganta del Cares)', 'Divine Gorge through dramatic cliffs', ARRAY['12km', '1000m cliffs', 'Asturias-León', 'Iconic'], true),
('Spain', 'Picos de Europa', 'Naranjo de Bulnes (Picu Urriellu)', 'Iconic limestone monolith', ARRAY['2519m', 'Climbing mecca', 'Views', 'Challenge'], true),
('Spain', 'Picos de Europa', 'Lagos de Covadonga', 'Glacial lakes pilgrimage site', ARRAY['Enol & Ercina', 'Pilgrimage', 'Pastoral', 'Accessible'], true),
('Spain', 'Picos de Europa', 'Fuente Dé Cable Car', 'Rapid access to high peaks', ARRAY['Torre Blanca', 'Cable car', 'Quick altitude', 'Views'], true),
('Spain', 'Picos de Europa', 'Three Massifs', 'Western Central and Eastern sections', ARRAY['Cornión', 'Urrieles', 'Ándara', 'Diverse'], true),
('Spain', 'Picos de Europa', 'Bulnes Village', 'Remote village with funicular', ARRAY['Funicular', 'Traditional', 'Remote', 'Authentic'], true),
('Spain', 'Sierra Nevada', 'Mulhacén', 'Mainland Spain''s highest', ARRAY['3482m', 'Non-technical summer', 'Andalusia', 'Summit'], true),
('Spain', 'Sierra Nevada', 'Veleta', 'Second highest in range', ARRAY['3398m', 'Road partway', 'Ski resort', 'Views'], true),
('Spain', 'Sierra Nevada', 'Alpujarras', 'White villages on southern slopes', ARRAY['Terraced farms', 'Traditional', 'Culture', 'Villages'], true),
('Spain', 'Sierra Nevada', 'High Route Traverse', 'Multi-day high mountain circuit', ARRAY['Circuit', 'Multi-day', 'Alpine', 'Challenging'], true),
('Spain', 'Camino de Santiago', 'Camino Francés', 'Most popular pilgrimage route', ARRAY['780km', 'Pyrenees', 'Santiago', 'Traditional'], true),
('Spain', 'Camino de Santiago', 'Camino del Norte', 'Northern coastal route', ARRAY['Basque Country to Galicia', 'Less crowded', 'Coastal', 'Beautiful'], true),
('Spain', 'Camino de Santiago', 'Camino Primitivo', 'Original route from Oviedo', ARRAY['Mountainous', 'Challenging', 'Original', 'Historic'], true),
('Spain', 'Camino de Santiago', 'Camino Portugués', 'From Porto to Santiago', ARRAY['Gentler', 'Portugal', 'Coastal', 'Popular'], true),
('Spain', 'Camino de Santiago', 'Via de la Plata', 'Seville to Santiago longest route', ARRAY['Longest', 'South to north', 'Historic', 'Cultural'], true),
('Spain', 'Other Regions', 'Sierra de Guadarrama', 'Madrid''s mountain escape', ARRAY['Peñalara (2428m)', 'Ski resorts', 'Accessible', 'Day trips'], true),
('Spain', 'Other Regions', 'Sierra de Gredos', 'Central Spain mountain range', ARRAY['Almanzor (2592m)', 'Mountain goat', 'Central', 'Wild'], true),
('Spain', 'Other Regions', 'Montserrat', 'Serrated mountain near Barcelona', ARRAY['Monastery', 'Rock climbing', 'Unique geology', 'Accessible'], true),
('Spain', 'Canary Islands', 'Teide National Park - Tenerife', 'Spain''s highest point', ARRAY['Mount Teide (3718m)', 'Volcanic', 'Lunar landscapes', 'UNESCO'], true),
('Spain', 'Canary Islands', 'La Palma', 'Volcanic trails and dark skies', ARRAY['Roque de los Muchachos', 'Caldera', 'Volcanic', 'Stargazing'], true),
('Spain', 'Canary Islands', 'El Hierro', 'Small Canary island', ARRAY['Volcanic hiking', 'Marine reserve', 'Remote', 'Pristine'], true),
('Spain', 'Other Regions', 'Picos de Urbión', 'Source of Duero River', ARRAY['Black Lagoon', 'Soria', 'Source', 'Remote'], true),
('Spain', 'Other Regions', 'Grazalema Natural Park', 'Spain''s wettest place', ARRAY['White villages', 'Pinsapo firs', 'Andalusia', 'Green'], true),

-- Sweden (10 regions) - Lines 329-338
('Sweden', NULL, 'Kungsleden (King''s Trail)', 'Sweden''s most famous trail', ARRAY['450km', 'Abisko to Hemavan', 'Lapland', 'Arctic', 'Classic'], true),
('Sweden', NULL, 'Abisko National Park', 'Northern lights and midnight sun', ARRAY['Lapporten', 'Kebnekaise access', 'Gateway', 'Iconic'], true),
('Sweden', NULL, 'Kebnekaise', 'Sweden''s highest mountain', ARRAY['2097m', 'Western non-technical', 'Eastern glacier', 'Summit'], true),
('Sweden', NULL, 'Sarek National Park', 'True wilderness with no trails', ARRAY['No paths', 'No huts', 'Experts only', 'Wild', 'Remote'], true),
('Sweden', NULL, 'Vindelfjällen Nature Reserve', 'Reindeer territory', ARRAY['Drottningleden trail', 'Less visited', 'Remote', 'Authentic'], true),
('Sweden', NULL, 'Padjelantaleden', '140km wilderness trail', ARRAY['Remote Lapland', 'Multi-day', 'Wilderness', 'Challenging'], true),
('Sweden', NULL, 'Höga Kusten (High Coast)', 'UNESCO World Heritage coast', ARRAY['Post-glacial uplift', 'Coastal cliffs', 'UNESCO', 'Unique'], true),
('Sweden', NULL, 'Sörmlandsleden', '1000km trail system near Stockholm', ARRAY['Stockholm proximity', 'Accessible', 'Multi-day', 'Forest'], true),
('Sweden', NULL, 'Fulufjället National Park', 'Sweden''s highest waterfall', ARRAY['Njupeskär', 'Old Tjikko tree', 'Waterfall', 'Ancient'], true),
('Sweden', NULL, 'Grövelsjön', 'Mountain station gateway', ARRAY['Norwegian border', 'Gateway', 'Traditional', 'Accessible'], true),

-- Switzerland (26 regions) - Lines 339-368
('Switzerland', 'Bernese Oberland', 'Jungfrau Region', 'Eiger Mönch Jungfrau trilogy', ARRAY['Top of Europe railway', 'Iconic', 'Lauterbrunnen', 'Classic'], true),
('Switzerland', 'Bernese Oberland', 'Lauterbrunnen Valley', '72 waterfalls in U-shaped valley', ARRAY['Trümmelbach Falls', 'Car-free villages', 'Glacial', 'Iconic'], true),
('Switzerland', 'Bernese Oberland', 'Mürren to Grütschalp', 'Car-free village with Bond location', ARRAY['Schilthorn (Piz Gloria)', 'Cliff-edge', 'James Bond', 'Views'], true),
('Switzerland', 'Bernese Oberland', 'Panorama Trail', 'Männlichen to Kleine Scheidegg', ARRAY['North Face views', 'Classic', 'Popular', 'Accessible'], true),
('Switzerland', 'Bernese Oberland', 'Schynige Platte', 'Alpine botanical garden', ARRAY['Panoramic', 'Cog railway', 'Botanical', 'Historic'], true),
('Switzerland', 'Bernese Oberland', 'Wengen', 'Car-free resort village', ARRAY['Jungfrau Marathon', 'Traditional', 'Car-free', 'Charming'], true),
('Switzerland', 'Bernese Oberland', 'First Cliff Walk', 'Suspension bridge with cliff views', ARRAY['Grindelwald', 'Bridge', 'Dramatic', 'Popular'], true),
('Switzerland', 'Valais (Wallis)', 'Zermatt & Matterhorn', 'Iconic pyramid peak', ARRAY['Matterhorn (4478m)', 'Car-free', 'Monte Rosa', 'Iconic'], true),
('Switzerland', 'Valais (Wallis)', 'Gornergrat Railway', 'Europe''s highest open-air railway', ARRAY['360° panoramas', 'Railway', 'Views', 'Accessible'], true),
('Switzerland', 'Valais (Wallis)', 'Five Lakes Walk', 'Matterhorn reflection lakes', ARRAY['Photo spots', 'Circuit', 'Accessible', 'Classic'], true),
('Switzerland', 'Valais (Wallis)', 'Haute Route', 'Chamonix to Zermatt classic', ARRAY['High-level', 'Glacier', 'Hut-to-hut', 'Iconic', 'Multi-day'], true),
('Switzerland', 'Valais (Wallis)', 'Saas-Fee', 'Pearl of the Alps', ARRAY['Glaciers', 'Allalinhorn (4027m easiest 4000er)', 'Car-free', 'Alpine'], true),
('Switzerland', 'Valais (Wallis)', 'Aletsch Glacier', 'Largest glacier in Alps', ARRAY['23km', 'UNESCO', 'Views', 'Glacial'], true),
('Switzerland', 'Valais (Wallis)', 'Lötschental', 'Unspoiled valley', ARRAY['Via ferrata', 'Traditional villages', 'Remote', 'Authentic'], true),
('Switzerland', 'Graubünden (Grisons)', 'Swiss National Park', 'Switzerland''s only national park', ARRAY['Ibex', 'Golden eagles', 'Pristine', 'Protected'], true),
('Switzerland', 'Graubünden (Grisons)', 'Engadine Valley', 'St. Moritz luxury region', ARRAY['Bernina Range', 'Piz Bernina (4049m)', 'Elegant', 'Lakes'], true),
('Switzerland', 'Graubünden (Grisons)', 'Via Alpina', '390km across Switzerland', ARRAY['14 passes', 'Multi-day', 'Alpine', 'Epic'], true),
('Switzerland', 'Graubünden (Grisons)', 'Corviglia', 'Above St. Moritz', ARRAY['Summer hiking', 'Winter skiing', 'Views', 'Resort'], true),
('Switzerland', 'Central Switzerland', 'Pilatus', 'Dragon legends mountain', ARRAY['Steepest cogwheel', 'Lucerne views', 'Legends', 'Accessible'], true),
('Switzerland', 'Central Switzerland', 'Rigi', 'Queen of the Mountains', ARRAY['Lake Lucerne', 'Sunrise viewpoint', 'Classic', 'Historic'], true),
('Switzerland', 'Central Switzerland', 'Titlis', 'Rotating cable car access', ARRAY['Glacier cave', 'Suspension bridge', 'Year-round', 'Popular'], true),
('Switzerland', 'Appenzell', 'Alpstein Massif', 'Cliffside restaurant hiking', ARRAY['Ebenalp', 'Aescher hut', 'Seealpsee', 'Unique'], true),
('Switzerland', 'Appenzell', 'Säntis', 'Highest in region with six-country views', ARRAY['2502m', 'Weather station', 'Views', 'Accessible'], true),
('Switzerland', 'Appenzell', 'Hoher Kasten', 'Revolving restaurant', ARRAY['Austria border', 'Restaurant', 'Views', 'Unique'], true),
('Switzerland', 'Ticino', 'Italian-speaking Switzerland', 'Mediterranean climate with palm trees', ARRAY['Verzasca Valley', 'Emerald pools', 'Palm trees', 'Southern'], true),
('Switzerland', 'Ticino', 'Monte Tamaro to Monte Lema', 'Classic ridge traverse', ARRAY['Lake Maggiore views', 'Ridge', 'Panoramic', 'Classic'], true),
('Switzerland', 'Ticino', 'Cardada-Cimetta', 'Above Locarno', ARRAY['Views', 'Cable car', 'Mediterranean', 'Southern'], true),
('Switzerland', 'Other Regions', 'Creux du Van', 'Rocky cirque - Swiss Grand Canyon', ARRAY['Jura', 'Cirque', 'Unique', 'Dramatic'], true),
('Switzerland', 'Other Regions', 'Lac de Joux', 'Jura region with watchmaking', ARRAY['Cross-country', 'Watchmaking heritage', 'Lakes', 'Cultural'], true),
('Switzerland', 'Other Regions', 'Monte San Salvatore', 'Above Lugano', ARRAY['Funicular', 'Lake Lugano views', 'Southern', 'Accessible'], true),

-- Turkey (2 regions) - Lines 369-370
('Turkey', NULL, 'Lycian Way', '540km Mediterranean coast with ruins', ARRAY['Ancient ruins', 'Turquoise coast', 'Multi-week', 'Historical'], true),
('Turkey', NULL, 'Kaçkar Mountains', 'Black Sea alpine region', ARRAY['Alpine terrain', 'Glacial lakes', 'Traditional villages', 'Remote'], true),

-- United Kingdom (30 regions) - Lines 371-401
('United Kingdom', 'England', 'Lake District', 'Wordsworth''s romantic lakes and fells', ARRAY['Scafell Pike (978m)', 'Helvellyn', 'Borrowdale', 'Literary'], true),
('United Kingdom', 'England', 'Peak District', 'Climbing and moorland paradise', ARRAY['Kinder Scout', 'Stanage Edge', 'Gritstone', 'Accessible'], true),
('United Kingdom', 'England', 'Yorkshire Dales', 'Three Peaks and limestone landscape', ARRAY['Pen-y-ghent', 'Whernside', 'Ingleborough', 'Malham Cove'], true),
('United Kingdom', 'England', 'Cotswolds', 'Gentle honey-stone villages', ARRAY['Rolling hills', 'Cotswold Way (164km)', 'Villages', 'Charming'], true),
('United Kingdom', 'England', 'Cornwall Coast Path', 'Dramatic Atlantic cliffs and beaches', ARRAY['Mining heritage', 'Land''s End', 'Beaches', 'Coastal'], true),
('United Kingdom', 'England', 'Dartmoor', 'Moorland wilderness', ARRAY['Granite tors', 'Wild ponies', 'Archaeology', 'Remote'], true),
('United Kingdom', 'England', 'South Downs', 'Chalk hills with Seven Sisters cliffs', ARRAY['South Downs Way', 'Coastal', 'Chalk', 'Accessible'], true),
('United Kingdom', 'England', 'North York Moors', 'Heather moorland with abbeys', ARRAY['Historic abbeys', 'Cleveland Way', 'Purple heather', 'Rural'], true),
('United Kingdom', 'Scotland', 'Scottish Highlands', 'Ben Nevis and dramatic glens', ARRAY['Ben Nevis (1345m UK highest)', 'Glen Coe', 'Fort William', 'Munros'], true),
('United Kingdom', 'Scotland', 'Cairngorms National Park', 'Plateau hiking with wildlife', ARRAY['CairnGorm', 'Ptarmigan', 'Red deer', 'Osprey', 'Plateau'], true),
('United Kingdom', 'Scotland', 'Isle of Skye', 'Dramatic island landscapes', ARRAY['Quiraing', 'Old Man of Storr', 'Fairy Pools', 'Cuillin', 'Iconic'], true),
('United Kingdom', 'Scotland', 'West Highland Way', 'Scotland''s classic long trail', ARRAY['154km', 'Glasgow to Fort William', 'Classic', 'Popular'], true),
('United Kingdom', 'Scotland', 'Torridon', 'Remote dramatic red sandstone peaks', ARRAY['Liathach', 'Beinn Eighe', 'Red deer', 'Wild', 'Remote'], true),
('United Kingdom', 'Scotland', 'Assynt', 'Isolated mountain wilderness', ARRAY['Suilven', 'Stac Pollaidh', 'Unique peaks', 'Remote', 'Geological'], true),
('United Kingdom', 'Scotland', 'Arran', 'Scotland in miniature', ARRAY['Goat Fell', 'Coastal and mountain', 'Island', 'Diverse'], true),
('United Kingdom', 'Scotland', 'Loch Lomond & Trossachs', 'Rob Roy country', ARRAY['Ben Lomond', 'Rob Roy', 'Accessible', 'National Park'], true),
('United Kingdom', 'Scotland', 'Glencoe', 'Three Sisters with dark history', ARRAY['Aonach Eagach ridge', 'Buachaille Etive Mòr', 'History', 'Dramatic'], true),
('United Kingdom', 'Scotland', 'Ben Nevis Range', 'UK''s highest mountain region', ARRAY['CMD Arête', 'Grey Corries', 'Mamores', 'Mountaineering'], true),
('United Kingdom', 'Scotland', 'Great Glen Way', '127km canal towpath', ARRAY['Fort William to Inverness', 'Canal', 'Gentle', 'Historic'], true),
('United Kingdom', 'Wales', 'Snowdonia', 'Wales''s highest peaks', ARRAY['Snowdon/Yr Wyddfa (1085m)', 'Six routes', 'Railway', 'National Park'], true),
('United Kingdom', 'Wales', 'Tryfan', 'Scrambling classic', ARRAY['Adam and Eve stones', 'Scrambling', 'Challenging', 'Iconic'], true),
('United Kingdom', 'Wales', 'Cadair Idris', 'Chair of Idris with legends', ARRAY['Legend', 'Poet or madman', 'Mountain', 'Mythology'], true),
('United Kingdom', 'Wales', 'Brecon Beacons', 'South Wales peaks', ARRAY['Pen y Fan (886m)', 'Waterfall Country', 'Accessible', 'National Park'], true),
('United Kingdom', 'Wales', 'Waterfall Country', 'Walk behind waterfalls', ARRAY['Sgwd yr Eira', 'Four Waterfalls Walk', 'Unique', 'Beautiful'], true),
('United Kingdom', 'Wales', 'Pembrokeshire Coast Path', '299km dramatic coastal scenery', ARRAY['Seals', 'Puffins', 'Beaches', 'Cliffs', 'Coastal'], true),
('United Kingdom', 'Wales', 'Black Mountains', 'Hay Bluff and book town', ARRAY['Gospel Pass', 'Hay-on-Wye', 'Literary', 'Ridges'], true),
('United Kingdom', 'Wales', 'Cambrian Mountains', 'Remote uplands', ARRAY['Plynlimon', 'Source of Severn/Wye', 'Wild', 'Remote'], true),
('United Kingdom', 'Wales', 'Gower Peninsula', 'First UK Area of Outstanding Beauty', ARRAY['Coastal walks', 'Beaches', 'AONB', 'Beautiful'], true),
('United Kingdom', 'Northern Ireland', 'Mourne Mountains', 'CS Lewis inspiration', ARRAY['Slieve Donard (850m NI highest)', 'Mourne Wall', 'Granite', 'Literary'], true),
('United Kingdom', 'Northern Ireland', 'Giant''s Causeway', '40000 basalt columns UNESCO', ARRAY['Coastal trails', 'Game of Thrones', 'Geological', 'Iconic'], true),
('United Kingdom', 'Northern Ireland', 'Causeway Coast Way', '53km coastal trail', ARRAY['Dramatic cliffs', 'Rope bridge', 'Coastal', 'Beautiful'], true)

ON CONFLICT (country, region, subregion) DO UPDATE SET
  description = EXCLUDED.description,
  key_features = EXCLUDED.key_features,
  is_active = EXCLUDED.is_active,
  updated_at = now();