-- Complete migration Part 2: Add remaining regions (Norway through UK)

INSERT INTO hiking_regions (country, region, subregion, description, key_features, is_active) VALUES
-- Norway (30+ regions) - Lines 211-240
('Norway', 'Western Fjords', 'Lysefjord', 'Iconic Norwegian fjord hikes', ARRAY['Preikestolen (Pulpit Rock)', 'Kjeragbolten', '604m cliff', 'Dramatic'], true),
('Norway', 'Western Fjords', 'Sognefjord', 'Norway''s longest and deepest fjord', ARRAY['Nærøyfjord UNESCO', 'Aurlandsdalen', '205km long', '1308m deep'], true),
('Norway', 'Western Fjords', 'Geirangerfjord', 'UNESCO fjord with waterfalls', ARRAY['Seven Sisters', 'Dalsnibba viewpoint', 'Iconic', 'Cruise ships'], true),
('Norway', 'Western Fjords', 'Hardangerfjord', 'Fruit orchards and glacier combination', ARRAY['Trolltunga (1180m cliff)', 'Folgefonna glacier', 'Fruit', 'Dramatic'], true),
('Norway', 'Western Fjords', 'Hjørundfjord', 'Less touristy authentic fishing villages', ARRAY['Sunnmøre Alps', 'Authentic', 'Less crowded', 'Beautiful'], true),
('Norway', 'Western Fjords', 'Nordfjord', 'Briksdal Glacier access', ARRAY['Briksdal', 'Loen Skylift', 'Mt. Skåla', 'Glacier'], true),
('Norway', 'Jotunheimen National Park', 'Besseggen Ridge', 'Norway''s most popular hike', ARRAY['Blue & green lakes', 'Ridge walk', 'Iconic', 'Gjende-Bessvatnet'], true),
('Norway', 'Jotunheimen National Park', 'Galdhøpiggen', 'Northern Europe''s highest peak', ARRAY['2469m', 'Glacier crossing', 'Guided', 'Summit'], true),
('Norway', 'Jotunheimen National Park', 'Glittertind', 'Second highest with permanent snow', ARRAY['2452m', 'Snow cap', 'Classic', 'Alpine'], true),
('Norway', 'Jotunheimen National Park', 'Hurrungane Peaks', 'Dramatic alpine spires', ARRAY['Store Skagastølstind', 'Advanced', 'Technical', 'Mountaineering'], true),
('Norway', 'Jotunheimen National Park', 'Gjende-Memurubu', 'DNT hut network classic', ARRAY['Hut-to-hut', 'Classic', 'Norwegian style', 'Traditional'], true),
('Norway', 'Jotunheimen National Park', 'Fannaråki', 'Ski touring in summer', ARRAY['Glacier approaches', 'Summer skiing', 'High altitude', 'Alpine'], true),
('Norway', 'Lofoten Islands', 'Reinebringen', 'Iconic vista over Reine village', ARRAY['Fjord views', 'Steep climb', 'Photography', 'Instagram'], true),
('Norway', 'Lofoten Islands', 'Kvalvika Beach', 'Remote Arctic beach hike', ARRAY['Mountain trail', 'Turquoise waters', 'Wild camping', 'Remote'], true),
('Norway', 'Lofoten Islands', 'Ryten', 'Panoramic island views', ARRAY['Kvalvika overlook', '360° views', 'Accessible', 'Beautiful'], true),
('Norway', 'Lofoten Islands', 'Munkebu Hut', 'Island crossing with traditional hut', ARRAY['Moskenesøya', 'Hut accommodation', 'Classic', 'Multi-day'], true),
('Norway', 'Lofoten Islands', 'Nusfjord & Å', 'Historic fishing villages', ARRAY['Coastal trails', 'Red cabins', 'Traditional', 'Authentic'], true),
('Norway', 'Lofoten Islands', 'Henningsvær', 'Venice of Lofoten', ARRAY['Football field island', 'Fishing village', 'Unique', 'Charming'], true),
('Norway', 'Romsdalseggen & Trollstigen', 'Romsdalseggen Ridge', '10km ridge with 360° views', ARRAY['Atlantic views', 'Åndalsnes', 'Dramatic', 'Panoramic'], true),
('Norway', 'Romsdalseggen & Trollstigen', 'Trollstigen', 'Mountain pass with waterfalls', ARRAY['Viewing platforms', 'Serpentine road', 'Accessible', 'Scenic drive'], true),
('Norway', 'Romsdalseggen & Trollstigen', 'Rampestreken Viewpoint', 'Cliff-edge platform above Åndalsnes', ARRAY['Cliff platform', 'Views', 'Accessible', 'Popular'], true),
('Norway', 'Other Regions', 'Hardangervidda', 'Europe''s largest mountain plateau', ARRAY['Vast tundra', 'Wild reindeer', 'Remote', 'Plateau'], true),
('Norway', 'Other Regions', 'Rondane National Park', 'Norway''s first national park', ARRAY['Rounded peaks', 'Multi-day loops', 'Wildlife', 'Historic'], true),
('Norway', 'Other Regions', 'Vesterålen Islands', 'North of Lofoten with whale watching', ARRAY['Queen''s Route', 'Whale watching', 'Less crowded', 'Authentic'], true),
('Norway', 'Other Regions', 'Senja Island', 'Norway in miniature', ARRAY['Segla peak', 'Ånderdalen', 'Dramatic', 'Diverse'], true),
('Norway', 'Other Regions', 'Lyngen Alps', 'Arctic skiing destination', ARRAY['Peaks from fjords', 'Skiing', 'Arctic', 'Remote'], true),
('Norway', 'Other Regions', 'Trollheimen', 'Home of the Trolls wilderness', ARRAY['Trondheim-Ålesund', 'Wilderness', 'Remote', 'Traditional'], true),
('Norway', 'Other Regions', 'Dovrefjell-Sunndalsfjella', 'Musk ox habitat', ARRAY['Snøhetta', 'Musk ox', 'Vast plateaus', 'Wildlife'], true),
('Norway', 'Other Regions', 'Helgeland Coast', 'Seven Sisters mountains', ARRAY['Torghatten hole-mountain', 'Coastal', 'Unique geology', 'Scenic'], true),
('Norway', 'Other Regions', 'North Cape Region', 'Arctic wilderness at northernmost point', ARRAY['Midnight sun', 'Northernmost', 'Arctic', 'Remote'], true),

-- Poland (7 regions) - Lines 241-247
('Poland', NULL, 'Tatra Mountains (High Tatras)', 'Poland''s Alps with dramatic peaks', ARRAY['Rysy (2499m)', 'Morskie Oko lake', 'Zakopane', 'Alpine'], true),
('Poland', NULL, 'Kasprowy Wierch', 'Cable car access to ridge walks', ARRAY['Slovakia border', 'Cable car', 'Accessible', 'Views'], true),
('Poland', NULL, 'Bieszczady Mountains', 'Remote eastern Carpathian wilderness', ARRAY['Poloniny meadows', 'Bison', 'Wolf habitat', 'Wild'], true),
('Poland', NULL, 'Karkonosze (Giant Mountains)', 'Shared Czech-Polish border range', ARRAY['Śnieżka (1603m)', 'Mountain huts', 'Cross-border', 'Traditional'], true),
('Poland', NULL, 'Pieniny National Park', 'Dunajec River Gorge', ARRAY['Trzy Korony', 'Raft trips', 'Gorge', 'Scenic'], true),
('Poland', NULL, 'Table Mountains (Góry Stołowe)', 'Sandstone formations with labyrinths', ARRAY['Szczeliniec Wielki', 'Labyrinth', 'Sandstone', 'Unique'], true),
('Poland', NULL, 'Babia Góra', 'Queen of Beskids', ARRAY['1725m', 'Weather extreme', 'Primeval forests', 'Challenging'], true),

-- Portugal (18 regions) - Lines 248-266
('Portugal', 'Mainland', 'Algarve Coast', 'Dramatic red sandstone cliffs', ARRAY['Seven Hanging Valleys', 'Benagil Cave', 'Beaches', 'Golden cliffs'], true),
('Portugal', 'Mainland', 'Costa de Caparica', 'Beach walks near Lisbon', ARRAY['Dunes', 'Lisbon proximity', 'Surfing', 'Accessible'], true),
('Portugal', 'Mainland', 'Serra da Estrela', 'Portugal''s highest mountain range', ARRAY['Torre (1993m)', 'Glacial valleys', 'Cheese', 'Ski resort'], true),
('Portugal', 'Mainland', 'Peneda-Gerês National Park', 'Only Portuguese national park', ARRAY['Waterfalls', 'Ancient villages', 'Wild horses', 'Northern'], true),
('Portugal', 'Mainland', 'Rota Vicentina', 'Southwest Alentejo coastal trails', ARRAY['Fishermen''s Trail', 'Historical Way', 'Coastal', 'Wild'], true),
('Portugal', 'Mainland', 'Sintra-Cascais', 'Westernmost Europe with palaces', ARRAY['Cabo da Roca', 'Palace trails', 'Atlantic', 'UNESCO'], true),
('Portugal', 'Madeira', 'Levada Walks', '3000km irrigation channel network', ARRAY['Laurel forests UNESCO', 'Subtropical', 'Year-round', 'Unique'], true),
('Portugal', 'Madeira', 'Pico Ruivo', 'Island''s highest peak', ARRAY['1862m', 'Sunrise hikes', 'Dramatic ridges', 'Summit'], true),
('Portugal', 'Madeira', 'Pico do Areeiro to Pico Ruivo', 'Most famous Madeira hike', ARRAY['Ridge traverse', 'Tunnels', 'Spectacular', 'Iconic'], true),
('Portugal', 'Madeira', 'Vereda dos Balcões', 'Balconies Trail viewpoint', ARRAY['Valley viewpoint', 'Easy', 'Accessible', 'Views'], true),
('Portugal', 'Madeira', 'Rabaçal Valley', '25 Fontes and Risco waterfalls', ARRAY['Waterfalls', 'Laurissilva forest', 'Popular', 'Beautiful'], true),
('Portugal', 'Madeira', 'Ponta de São Lourenço', 'Dramatic eastern peninsula', ARRAY['Volcanic formations', 'Arid landscape', 'Coastal', 'Unique'], true),
('Portugal', 'Madeira', 'Caldeirão Verde', 'Waterfall hike through tunnels', ARRAY['Tunnels', 'Lush vegetation', 'Adventure', 'Green'], true),
('Portugal', 'Azores', 'Pico Island', 'Portugal''s highest mountain', ARRAY['Mount Pico (2351m)', 'Volcanic ascent', 'UNESCO', 'Summit'], true),
('Portugal', 'Azores', 'São Miguel', 'Crater lakes and hot springs', ARRAY['Sete Cidades', 'Terra Nostra', 'Furnas', 'Volcanic'], true),
('Portugal', 'Azores', 'Flores Island', 'Westernmost Europe with waterfalls', ARRAY['20+ waterfalls', 'Basalt columns', 'Remote', 'Pristine'], true),
('Portugal', 'Azores', 'Faial Island', 'Caldeira crater rim walk', ARRAY['Capelinhos volcano', 'Whaling heritage', 'Mid-Atlantic', 'Views'], true),
('Portugal', 'Azores', 'São Jorge', 'Fajãs coastal plains', ARRAY['Cliffs', 'Cheese production', 'Unique', 'Traditional'], true),
('Portugal', 'Azores', 'Terceira', 'Volcanic caves and tubes', ARRAY['Algar do Carvão', 'Monte Brasil', 'Caves', 'Volcanic'], true),

-- Romania, Serbia, Slovakia, Slovenia (Lines 267-298)
('Romania', NULL, 'Făgăraș Mountains', 'Romania''s highest range', ARRAY['Moldoveanu (2544m)', 'Transfăgărășan Road', 'Bâlea Lake', 'Challenging'], true),
('Romania', NULL, 'Multi-day Ridge Traverse (Făgăraș)', '7-day high-altitude route', ARRAY['Glacial lakes', 'Challenging', 'Wild', 'Multi-day'], true),
('Romania', NULL, 'Bucegi Mountains', 'Rock formations and plateau', ARRAY['Babele & Sphinx', 'Omu (2505m)', 'Via ferratas', 'Peleș Castle'], true),
('Romania', NULL, 'Piatra Craiului', 'Knife-edge limestone ridge', ARRAY['25km traverse', 'Chamois', 'Technical', 'Dramatic'], true),
('Romania', NULL, 'Retezat National Park', '80+ glacial lakes', ARRAY['Lake Bucura', 'Retezat (2509m)', 'Wilderness', 'Bears'], true),
('Romania', NULL, 'Apuseni Mountains', 'Karst caves and traditional villages', ARRAY['Scărișoara Ice Cave', 'Traditional', 'Gentle', 'Cultural'], true),
('Romania', NULL, 'Rodna Mountains', 'Remote primeval forests', ARRAY['Pietrosul Rodnei (2303m)', 'Primeval', 'Remote', 'Wild'], true),
('Romania', NULL, 'Ceahlău Massif', 'Olympus of Romania', ARRAY['Toaca peak', 'Legends', 'Mythology', 'Spiritual'], true),
('Romania', NULL, 'Carpathian Wilderness', 'Europe''s large carnivore habitat', ARRAY['Brown bear', 'Wolf', 'Lynx', 'Wildlife'], true),
('Serbia', NULL, 'Kopaonik National Park', 'Serbia''s largest ski resort', ARRAY['Pančić''s Peak (2017m)', 'Spa heritage', 'Accessible', 'Resort'], true),
('Serbia', NULL, 'Tara National Park', 'Primeval forests and canyon', ARRAY['Drina canyon', 'Viewpoints', 'Wildlife', 'Pristine'], true),
('Serbia', NULL, 'Stara Planina', 'Remote eastern mountains', ARRAY['Midžor (2169m)', 'Bulgarian border', 'Wild', 'Remote'], true),
('Serbia', NULL, 'Đerdap (Iron Gates)', 'Danube gorge with fortress', ARRAY['Golubac Fortress', 'Lepenski Vir', 'Archaeological', 'River'], true),
('Serbia', NULL, 'Fruška Gora', 'Monasteries and wine region', ARRAY['Danube views', 'Wine', 'Monasteries', 'Gentle'], true),
('Slovakia', NULL, 'High Tatras (Vysoké Tatry)', 'Carpathians highest peaks', ARRAY['Gerlachovský štít (2655m)', 'Alpine', 'Huts', 'Challenging'], true),
('Slovakia', NULL, 'Lomnický štít', 'Cable car access to views', ARRAY['Observatory', 'Panoramic', 'Accessible', 'Popular'], true),
('Slovakia', NULL, 'Rysy', 'Accessible highest peak', ARRAY['Slovakia-Poland border', 'Summit', 'Popular', 'Views'], true),
('Slovakia', NULL, 'Low Tatras (Nízke Tatry)', 'Gentler than High Tatras', ARRAY['Chopok', 'Ďumbier (2043m)', 'Ski resorts', 'Accessible'], true),
('Slovakia', NULL, 'Slovak Paradise (Slovenský raj)', 'Gorges with ladders and chains', ARRAY['Suchá Belá canyon', 'Via ferrata style', 'Adventure', 'Technical'], true),
('Slovakia', NULL, 'Malá Fatra', 'Traditional shepherd culture', ARRAY['Veľký Rozsutec', 'Jánošíkove diery', 'Folklore', 'Cultural'], true),
('Slovakia', NULL, 'Pieniny', 'Dunajec gorge shared with Poland', ARRAY['Tri koruny', 'Rafting', 'Cross-border', 'Scenic'], true),
('Slovakia', NULL, 'Slovenské Rudohorie', 'Ore Mountains with mining heritage', ARRAY['Mining heritage', 'Diverse', 'Historical', 'Gentle'], true),
('Slovenia', NULL, 'Triglav National Park', 'Slovenia''s only national park', ARRAY['Mount Triglav (2864m)', 'National symbol', 'Vrata Valley', 'Alpine'], true),
('Slovenia', NULL, 'Seven Lakes Valley', 'Pristine glacial lakes circuit', ARRAY['Alpine flowers', 'Hut-to-hut', 'Peaceful', 'Beautiful'], true),
('Slovenia', NULL, 'Krma Valley', 'Less crowded Triglav approach', ARRAY['Traditional pastures', 'Peaceful', 'Authentic', 'Alpine'], true),
('Slovenia', NULL, 'Lake Bled', 'Fairy-tale lake with island church', ARRAY['Bled Castle', 'Vintgar Gorge', 'Ojstrica', 'Iconic'], true),
('Slovenia', NULL, 'Lake Bohinj', 'Larger quieter lake', ARRAY['Savica Waterfall', 'Vogel cable car', 'Tranquil', 'Swimming'], true),
('Slovenia', NULL, 'Kranjska Gora', 'Planica ski jumps valley', ARRAY['Vršič Pass (50 hairpins)', 'Russian Chapel', 'Ski resort', 'Alpine'], true),
('Slovenia', NULL, 'Soča Valley', 'Emerald river paradise', ARRAY['Boka (144m)', 'Kozjak falls', 'WWI history', 'Turquoise'], true),
('Slovenia', NULL, 'Kamnik-Savinja Alps', 'Logarska Dolina glacial valley', ARRAY['Rinka Waterfall', 'Ojstrica viewpoint', 'Glacial valley', 'Beautiful'], true),
('Slovenia', NULL, 'Velika Planina', 'Traditional shepherd settlement', ARRAY['Wooden huts', 'Plateau', 'Cheese', 'Summer pastures', 'Unique'], true),
('Slovenia', NULL, 'Škocjan Caves Region', 'UNESCO caves with surface trails', ARRAY['Karst landscape', 'Underground', 'UNESCO', 'Unique'], true),
('Slovenia', NULL, 'Alpe Adria Trail', '750km Austria to Adriatic', ARRAY['Multi-country', 'Multi-day', 'Cultural', 'Long-distance'], true)

ON CONFLICT (country, region, subregion) DO UPDATE SET
  description = EXCLUDED.description,
  key_features = EXCLUDED.key_features,
  is_active = EXCLUDED.is_active,
  updated_at = now();