-- Complete migration: Add remaining hiking regions (France onwards to UK)

INSERT INTO hiking_regions (country, region, subregion, description, key_features, is_active) VALUES
-- France (27 regions) - Lines 74-100
('France', 'French Alps', 'Chamonix-Mont Blanc', 'Birthplace of alpinism and mountaineering', ARRAY['Tour du Mont Blanc', 'Aiguille du Midi', 'Lac Blanc', 'Alpine heritage'], true),
('France', 'French Alps', 'Argentière Valley', 'High alpine glacier terrain', ARRAY['Argentière Glacier', 'Grands Montets', 'Advanced terrain', 'Glaciers'], true),
('France', 'French Alps', 'Mont Blanc Massif', 'Europe''s highest peak region', ARRAY['4808m', 'Multiple routes', 'Refuges', 'Iconic'], true),
('France', 'French Alps', 'Vanoise National Park', 'France''s first national park from 1963', ARRAY['Grande Casse (3855m)', 'Ibex', 'Alpine flora', 'Wildlife'], true),
('France', 'French Alps', 'Val d''Isère-Tignes', 'High-altitude trails with summer skiing', ARRAY['Espace Killy', 'Summer skiing', 'Resort', 'Alpine'], true),
('France', 'French Alps', 'Pralognan-la-Vanoise', 'Gateway village with Savoyard culture', ARRAY['Traditional culture', 'Cheese', 'Gateway', 'Authentic'], true),
('France', 'French Alps', 'Écrins National Park', 'Remote alpine wilderness with 4000m peaks', ARRAY['La Meije (3983m)', 'Barre des Écrins (4102m)', 'Glaciers', 'Wild'], true),
('France', 'French Alps', 'La Grave', 'Legendary freeriding town with wild terrain', ARRAY['Wild terrain', 'Authentic culture', 'Off-piste', 'Remote'], true),
('France', 'French Alps', 'Vallée de la Clarée', 'Undiscovered valley with traditional villages', ARRAY['Traditional villages', 'Larch forests', 'Peaceful', 'Authentic'], true),
('France', 'French Alps', 'Queyras Regional Park', 'High-altitude isolated villages', ARRAY['GR58 tour', 'Fort Queyras', 'Traditional culture', 'Remote'], true),
('France', 'French Alps', 'Mercantour National Park', 'Maritime Alps with prehistoric art', ARRAY['Vallée des Merveilles', 'Mediterranean flora', 'Wolves', 'Prehistoric'], true),
('France', 'French Alps', 'Beaufortain Massif', 'Famous Beaufort cheese region', ARRAY['Mont Blanc views', 'Cormet de Roselend', 'Cheese', 'Pastoral'], true),
('France', 'French Alps', 'Aravis Range', 'Reblochon cheese country with limestone peaks', ARRAY['La Clusaz', 'Le Grand Bornand', 'Cheese', 'Limestone'], true),
('France', 'French Alps', 'Haute-Savoie Lakes', 'Lake Annecy and Geneva region trails', ARRAY['Lake Annecy', 'Lake Geneva', 'Scenic', 'Water'], true),
('France', 'Pyrenees', 'Pyrenees National Park', 'French Pyrenees with UNESCO cirque', ARRAY['Cirque de Gavarnie UNESCO', 'Vignemale (3298m)', 'Waterfalls', 'Border'], true),
('France', 'Pyrenees', 'GR10', '870km coast-to-coast trek', ARRAY['Atlantic to Mediterranean', 'Pyrenees traverse', 'Multi-week', 'Epic'], true),
('France', 'Pyrenees', 'Pic du Midi de Bigorre', 'Observatory with cable car access', ARRAY['Observatory', 'Cable car', 'Panoramic', 'Astronomy'], true),
('France', 'Pyrenees', 'Néouvielle Nature Reserve', '70+ lakes in pristine wilderness', ARRAY['Lakes', 'Wilderness', 'Pic Long', 'Alpine'], true),
('France', 'Pyrenees', 'Ariège Pyrenees', 'Quieter eastern section with Cathar history', ARRAY['Cathar castles', 'Less crowded', 'Historical'], true),
('France', 'Corsica', 'GR20', 'Europe''s toughest hiking trail', ARRAY['180km', '2 weeks', 'Mountain refuges', 'Granite peaks', 'Challenging'], true),
('France', 'Corsica', 'Bavella Needles', 'Dramatic granite spires', ARRAY['Aiguilles de Bavella', 'Climbing', 'Granite', 'Iconic'], true),
('France', 'Corsica', 'Monte Cinto', 'Corsica''s highest peak', ARRAY['2706m', 'Highest', 'Summit', 'Alpine'], true),
('France', 'Corsica', 'Mare e Monti', 'Sea and Mountains trail on west coast', ARRAY['Coastal', 'Villages', 'Scenic', 'Multi-day'], true),
('France', 'Other Regions', 'Jura Mountains', 'Karst landscapes with cross-country skiing heritage', ARRAY['Reculée de Baume', 'Karst', 'Cross-country', 'Forests'], true),
('France', 'Other Regions', 'Vosges Mountains', 'Gentler forested mountains', ARRAY['Grand Ballon (1424m)', 'Forests', 'Alsace access', 'Gentle'], true),
('France', 'Other Regions', 'Massif Central', 'Volcanic region of Auvergne', ARRAY['Puy de Dôme', 'Volcanoes', 'Cévennes', 'Central France'], true),
('France', 'Other Regions', 'Provence', 'Mediterranean hills and gorges', ARRAY['Verdon Gorge', 'Luberon', 'Lavender fields', 'Mediterranean'], true),
('France', 'Other Regions', 'Brittany Coast', 'Celtic heritage coastal path', ARRAY['GR34', 'Headlands', 'Celtic', 'Coastal'], true),
('France', 'Other Regions', 'Normandy Cliffs', 'D-Day beaches and dramatic cliffs', ARRAY['Étretat', 'D-Day beaches', 'History', 'Coastal'], true),

-- Germany (9 regions) - Lines 103-111
('Germany', NULL, 'Bavarian Alps', 'Germany''s Alpine region with highest peak', ARRAY['Zugspitze (2962m)', 'Garmisch', 'Partnach Gorge', 'Alpine'], true),
('Germany', NULL, 'Berchtesgaden National Park', 'Dramatic limestone Alps with historic sites', ARRAY['Watzmann (2713m)', 'Königssee', 'Eagle''s Nest', 'WWII history'], true),
('Germany', NULL, 'Allgäu Alps', 'Neuschwanstein Castle region', ARRAY['Castle views', 'Oberstdorf', 'Family-friendly', 'Fairy-tale'], true),
('Germany', NULL, 'Black Forest (Schwarzwald)', 'Dense coniferous forests', ARRAY['Feldberg (1493m)', 'Cuckoo clocks', 'Rolling terrain', 'Traditional'], true),
('Germany', NULL, 'Saxon Switzerland', 'Sandstone climbing paradise', ARRAY['Bastei Bridge', 'Elbe valley', 'Rock formations', 'Climbing'], true),
('Germany', NULL, 'Harz Mountains', 'Witch folklore and historic steam trains', ARRAY['Brocken (1141m)', 'Steam railway', 'Forests', 'Folklore'], true),
('Germany', NULL, 'Eifel Region', 'Volcanic lakes and forests', ARRAY['Maare (lakes)', 'Volcanic', 'German-Belgian border', 'Nature'], true),
('Germany', NULL, 'Bavarian Forest', 'Germany''s oldest national park', ARRAY['Rachel peak', 'Primeval forests', 'Lynx habitat', 'Wilderness'], true),
('Germany', NULL, 'Swabian Jura', 'Limestone plateau with caves', ARRAY['Caves', 'Castles', 'Danube source', 'Karst'], true),

-- Greece (13 regions) - Lines 112-124
('Greece', NULL, 'Mount Olympus', 'Home of the Greek gods', ARRAY['Mytikas (2918m)', '2-day refuge ascent', 'Mythology', 'Iconic'], true),
('Greece', NULL, 'Zagori & Vikos', 'Stone villages and deepest gorge', ARRAY['Vikos Gorge (deepest)', '46 villages', 'Stone bridges', 'Traditional'], true),
('Greece', NULL, 'Astraka Refuge & Dragon Lake', 'High mountain lakes in Tymfi massif', ARRAY['Dragon Lake', 'Tymfi', 'Alpine', 'Refuge'], true),
('Greece', 'Crete', 'White Mountains (Lefka Ori)', 'Samaria Gorge region', ARRAY['Samaria (16km longest)', 'Pachnes (2453m)', 'Wild', 'Gorge'], true),
('Greece', 'Crete', 'Psiloritis (Mount Ida)', 'Zeus''s birthplace in mythology', ARRAY['Nida Plateau', '2456m', 'Mythology', 'Highest Crete'], true),
('Greece', NULL, 'Meteora', 'Monasteries on rock pillars', ARRAY['UNESCO', 'Sunrise hikes', 'Unique geology', 'Spiritual'], true),
('Greece', NULL, 'Mount Athos', 'Monastic republic hiking pilgrimage', ARRAY['Men only', 'Byzantine heritage', 'Spiritual', 'Autonomous'], true),
('Greece', NULL, 'Pelion Peninsula', 'Mythical centaur territory', ARRAY['Coastal mountains', 'Traditional villages', 'Beaches', 'Mythology'], true),
('Greece', NULL, 'Pindus Range', 'Spine of Greece with shepherd culture', ARRAY['Tzoumerka', 'Shepherd culture', 'Remote', 'Central'], true),
('Greece', NULL, 'Mount Parnassus', 'Delphi''s sacred mountain', ARRAY['Liakoura (2457m)', 'Ski resort', 'Ancient', 'Sacred'], true),
('Greece', NULL, 'Taygetos Mountain', 'Sparta''s dramatic backdrop', ARRAY['Profitis Ilias (2404m)', 'Mani views', 'Rugged', 'Southern'], true),
('Greece', NULL, 'Peloponnese Trails', 'Ancient sites with gorge hiking', ARRAY['Lousios Gorge', 'Menalon Trail', 'Ancient sites', 'Historical'], true),

-- Iceland (10 regions) - Lines 124-133
('Iceland', NULL, 'Landmannalaugar', 'Colored rhyolite mountains with hot springs', ARRAY['Hot springs', 'Brennisteinsalda', 'Laugavegur start', 'Volcanic'], true),
('Iceland', NULL, 'Laugavegur Trail', 'Iceland''s most famous trek', ARRAY['55km', '4 days', 'Glaciers', 'Colorful peaks', 'Classic'], true),
('Iceland', NULL, 'Fimmvörðuháls', 'Trek between two glaciers', ARRAY['Eyjafjallajökull', 'Mýrdalsjökull', '2010 craters', 'Waterfalls'], true),
('Iceland', NULL, 'Þórsmörk (Thorsmork)', 'Valley surrounded by glaciers', ARRAY['Forest of Thor', 'Valahnúkur', 'River crossings', 'Protected'], true),
('Iceland', NULL, 'Hornstrandir Nature Reserve', 'Remote Arctic wilderness with no roads', ARRAY['Arctic fox', 'Abandoned villages', 'Westfjords', 'Pristine'], true),
('Iceland', NULL, 'Snæfellsnes Peninsula', 'Iceland in miniature', ARRAY['Snæfellsjökull glacier', 'Kirkjufell', 'Diverse', 'Accessible'], true),
('Iceland', NULL, 'Reykjanes Peninsula', 'Volcanic and geothermal area', ARRAY['Bridge Between Continents', 'Geothermal', 'Reykjavik access', 'Active'], true),
('Iceland', NULL, 'Askja & Highlands', 'Remote volcanic interior', ARRAY['Viti crater', '4WD required', 'Summer only', 'Lunar landscape'], true),
('Iceland', NULL, 'Skaftafell (Vatnajökull National Park)', 'Glacier tongues and waterfalls', ARRAY['Svartifoss', 'Glacier views', 'National park', 'Accessible'], true),
('Iceland', NULL, 'Dettifoss Region', 'Europe''s most powerful waterfall', ARRAY['Jökulsárgljúfur canyon', 'Power', 'Canyon', 'Raw nature'], true),

-- Ireland (9 regions) - Lines 134-142
('Ireland', NULL, 'Wicklow Mountains', 'Garden of Ireland', ARRAY['Wicklow Way (127km)', 'Glendalough monastery', 'Accessible', 'Monastic'], true),
('Ireland', NULL, 'MacGillycuddy''s Reeks', 'Ireland''s highest peaks', ARRAY['Carrauntoohil (1038m)', 'Coomloughra Horseshoe', 'Kerry', 'Challenging'], true),
('Ireland', NULL, 'Ring of Kerry', 'Scenic coastal loop', ARRAY['Torc Mountain', 'Ladies View', 'Villages', 'Iconic'], true),
('Ireland', NULL, 'Connemara', 'Wild Atlantic landscapes', ARRAY['Twelve Bens', 'Kylemore Abbey', 'Bogs', 'Rugged'], true),
('Ireland', NULL, 'Dingle Peninsula', 'Ancient sites and coastal beauty', ARRAY['Mount Brandon (952m)', 'Slea Head', 'Blasket Islands', 'Celtic'], true),
('Ireland', NULL, 'Cliffs of Moher', 'Dramatic Atlantic cliffs', ARRAY['214m cliffs', 'Coastal path', 'Seabirds', 'Iconic'], true),
('Ireland', NULL, 'Burren', 'Unique limestone karst landscape', ARRAY['Rare flora', 'Ancient sites', 'Lunar landscape', 'Geology'], true),
('Ireland', NULL, 'Slieve League', 'Among Europe''s highest sea cliffs', ARRAY['601m cliffs', 'Less touristy', 'Atlantic', 'Dramatic'], true),
('Ireland', NULL, 'Donegal Highlands', 'Remote northern wilderness', ARRAY['Slieve Snaght', 'Glenveagh', 'Remote', 'Wild'], true),

-- Italy - Dolomites (10 regions) - Lines 143-152
('Italy', 'Dolomites', 'Cortina d''Ampezzo', 'Queen of the Dolomites', ARRAY['Tre Cime', 'Cinque Torri', '1956 Olympics', 'Ladin culture'], true),
('Italy', 'Dolomites', 'Val Gardena (Gröden)', 'Iconic Dolomite views', ARRAY['Seceda viewpoint', 'Puez-Odle', 'Sella Ronda', 'Ladino culture'], true),
('Italy', 'Dolomites', 'Alpe di Siusi (Seiser Alm)', 'Europe''s largest alpine meadow', ARRAY['Plateau', 'Schlern', 'Wildflowers', 'Pastoral'], true),
('Italy', 'Dolomites', 'Tre Cime di Lavaredo', 'Iconic three peaks', ARRAY['Rifugio circuit', 'Sesto', 'Photography', 'Iconic'], true),
('Italy', 'Dolomites', 'Marmolada', 'Queen of the Dolomites - highest peak', ARRAY['3343m', 'Glacier', 'WWI history', 'Cable car'], true),
('Italy', 'Dolomites', 'Sella Group', 'Circumnavigation routes', ARRAY['Via ferratas', 'Passo Pordoi', 'Circuit', 'Technical'], true),
('Italy', 'Dolomites', 'Pale di San Martino', 'Pala group pristine wilderness', ARRAY['Rolle Pass', 'Pristine', 'Remote', 'Limestone'], true),
('Italy', 'Dolomites', 'Pragser Wildsee (Lago di Braies)', 'Turquoise lake surrounded by peaks', ARRAY['Lake', 'Turquoise', 'Photography', 'Iconic'], true),
('Italy', 'Dolomites', 'Alta Via 1 & Alta Via 2', 'Classic multi-day Dolomite traverses', ARRAY['Rifugio-to-rifugio', 'Multi-day', 'Classic', 'Huts'], true),
('Italy', 'Dolomites', 'Brenta Dolomites', 'Western Dolomites massif separated from main range', ARRAY['Via delle Bocchette', 'Madonna di Campiglio', 'Cima Tosa (3173m)', 'Via ferrata paradise', 'UNESCO', 'Wild and rugged'], true),

-- Italy - Other regions (20+ regions) - Lines 154-178
('Italy', 'Aosta Valley', 'Gran Paradiso National Park', 'Italy''s first national park', ARRAY['Gran Paradiso (4061m)', 'Ibex', 'Alpine flora', 'Wildlife'], true),
('Italy', 'Aosta Valley', 'Mont Blanc South Face', 'Italian side of Mont Blanc', ARRAY['Courmayeur', 'Val Ferret', 'Tour du Mont Blanc', 'Luxury'], true),
('Italy', 'Aosta Valley', 'Matterhorn (Cervino) Italian Side', 'Italian approach to iconic peak', ARRAY['Breuil-Cervinia', 'Theodul Pass', 'Zermatt connection', 'Views'], true),
('Italy', 'Aosta Valley', 'Monte Rosa', 'Second highest Alpine massif', ARRAY['Gressoney valleys', '4000m peaks', 'Glaciers', 'Alpine'], true),
('Italy', 'Ligurian Coast', 'Cinque Terre - Sentiero Azzurro', 'Blue Trail connecting five villages', ARRAY['Monterosso', 'Vernazza', 'Corniglia', 'Manarola', 'Riomaggiore'], true),
('Italy', 'Ligurian Coast', 'Cinque Terre - Via dell''Amore', 'Path of Love cliffsides', ARRAY['Romantic', 'Cliffsides', 'Currently closed', 'Restoration'], true),
('Italy', 'Ligurian Coast', 'Cinque Terre - High Path', 'Ridge trail above villages', ARRAY['Sentiero Rosso', 'Vineyard views', 'Less crowded', 'Panoramic'], true),
('Italy', 'Ligurian Coast', 'Cinque Terre - Sanctuary Trails', 'Ancient pilgrimage paths to hilltop churches', ARRAY['Pilgrimage', 'Churches', 'Traditional', 'Spiritual'], true),
('Italy', 'Ligurian Coast', 'Portovenere Extension', 'Dramatic promontory beyond Cinque Terre', ARRAY['Byron''s Grotto', 'Gulf of Poets', 'Extension', 'Coastal'], true),
('Italy', 'Italian Lakes', 'Lake Como', 'Stunning alpine lake trails', ARRAY['Sentiero del Viandante', 'Grigne', 'Villages', 'Elegant'], true),
('Italy', 'Italian Lakes', 'Lake Garda', 'Italy''s largest lake', ARRAY['Monte Baldo', 'Coastal paths', 'Mediterranean', 'Diverse'], true),
('Italy', 'Italian Lakes', 'Lake Maggiore', 'Borromean Islands views', ARRAY['Mottarone', 'Islands', 'Alpine-Mediterranean', 'Scenic'], true),
('Italy', 'Italian Lakes', 'Lake Orta', 'Quieter alternative to Como', ARRAY['San Giulio Island', 'Peaceful', 'Traditional', 'Hidden gem'], true),
('Italy', 'Central Italy', 'Gran Sasso & Monti della Laga', 'Apennines highest peak', ARRAY['Corno Grande (2912m)', 'Campo Imperatore', 'Abruzzo', 'Wild'], true),
('Italy', 'Central Italy', 'Majella National Park', 'Rugged Apennines with hermitages', ARRAY['Hermitages', 'Wildlife', 'Remote', 'Spiritual'], true),
('Italy', 'Central Italy', 'Sibillini Mountains', 'Piano Grande wildflowers', ARRAY['Wildflowers', 'Castelluccio', 'Earthquake recovery', 'Colorful'], true),
('Italy', 'Central Italy', 'Tuscany Hills', 'Chianti and Val d''Orcia trails', ARRAY['Chianti', 'Val d''Orcia', 'Wine', 'Gentle'], true),
('Italy', 'Southern Italy', 'Amalfi Coast', 'UNESCO coastal paradise', ARRAY['Path of the Gods', 'Positano', 'Ravello', 'Dramatic'], true),
('Italy', 'Southern Italy', 'Pollino National Park', 'Wildest Apennines', ARRAY['Calabria-Basilicata', 'Pino Loricato', 'Wild', 'Remote'], true),
('Italy', 'Southern Italy', 'Aspromonte', 'Calabria''s toe region', ARRAY['Montalto', 'Bergamot groves', 'Southern', 'Wild'], true),
('Italy', 'Southern Italy', 'Cilento National Park', 'Coastal mountains with Greek temples', ARRAY['Paestum temples', 'Mediterranean', 'Coastal', 'Ancient'], true),
('Italy', 'Islands - Sicily', 'Mount Etna', 'Europe''s most active volcano', ARRAY['3357m', 'Crater hikes', 'Lava flows', 'UNESCO', 'Active'], true),
('Italy', 'Islands - Sicily', 'Madonie & Nebrodi', 'Mountain parks with traditional life', ARRAY['Traditional villages', 'Diverse ecology', 'Cultural', 'Rural'], true),
('Italy', 'Islands - Sardinia', 'Selvaggio Blu', 'One of Europe''s toughest trails', ARRAY['Cliff-side', 'Technical', 'Multi-day', 'Expert only'], true),
('Italy', 'Islands - Sardinia', 'Gennargentu', 'Island''s highest peaks', ARRAY['Shepherd culture', 'Traditional', 'Central', 'Authentic'], true),
('Italy', 'Islands - Sardinia', 'Supramonte', 'Karst plateau with deep gorge', ARRAY['Gorropu Gorge', 'Nuragic archaeology', 'Karst', 'Cultural'], true),

-- Kosovo, Latvia, Liechtenstein, Lithuania, Luxembourg (Lines 179-194)
('Kosovo', NULL, 'Accursed Mountains (Bjeshkët e Nemuna)', 'Peaks of the Balkans section', ARRAY['Gjeravica (2656m)', 'Remote', 'Traditional', 'Cross-border'], true),
('Kosovo', NULL, 'Rugova Valley', 'Dramatic gorge with via ferrata', ARRAY['Rugova Gorge', 'Climbing', 'Monastery', 'Canyon'], true),
('Kosovo', NULL, 'Šar Mountains', 'Shared with North Macedonia', ARRAY['Ljuboten', 'Cross-border', 'Alpine', 'Traditional'], true),
('Latvia', NULL, 'Gauja National Park', 'Sandstone cliffs and medieval castles', ARRAY['Castles', 'River valley', 'Forests', 'Medieval'], true),
('Latvia', NULL, 'Slītere National Park', 'Baltic coast with Livonian culture', ARRAY['Kolka Cape', 'Coastal', 'Livonian heritage', 'Remote'], true),
('Latvia', NULL, 'Kemeri National Park', 'Bog boardwalks and sulphur springs', ARRAY['Great Kemeri Bog', 'Springs', 'Coastal', 'Wellness'], true),
('Liechtenstein', NULL, 'Rätikon Range', 'Border ridges with Austria and Switzerland', ARRAY['Limestone peaks', 'Cross-border', 'Alpine', 'Small country'], true),
('Liechtenstein', NULL, 'Route 66 (Liechtenstein Trail)', '75km through all 11 communes', ARRAY['Hut-to-hut', 'Complete traverse', 'Villages', 'National'], true),
('Liechtenstein', NULL, 'Fürstensteig', 'Classic ridge trail with via ferrata', ARRAY['Via ferrata', 'Panoramic', 'Historic', 'Technical'], true),
('Liechtenstein', NULL, 'Three Sisters (Drei Schwestern)', 'Border peaks with historic routes', ARRAY['Border peaks', 'Historic', 'Three summits', 'Iconic'], true),
('Lithuania', NULL, 'Curonian Spit', 'UNESCO sand dune peninsula', ARRAY['Baltic Sea', 'Curonian Lagoon', 'Unique', 'Dunes'], true),
('Lithuania', NULL, 'Aukštaitija National Park', 'Lake district with forests', ARRAY['Traditional villages', 'Canoeing', 'Wildlife', 'Lakes'], true),
('Lithuania', NULL, 'Dzūkija National Park', 'Pine forests with traditional culture', ARRAY['Mushrooms', 'Traditional', 'Forests', 'Cultural'], true),
('Luxembourg', NULL, 'Mullerthal Trail', 'Little Switzerland with rock formations', ARRAY['Rock formations', '3 loop routes', 'Forests', 'Unique geology'], true),
('Luxembourg', NULL, 'Moselle Valley', 'Wine region trails', ARRAY['River paths', 'Vineyards', 'Villages', 'Wine culture'], true),
('Luxembourg', NULL, 'Our Valley', 'River trails with medieval castle', ARRAY['Vianden Castle', 'German border', 'River', 'Medieval'], true),
('Luxembourg', NULL, 'Ardennes Luxembourg', 'WWII Battle of the Bulge region', ARRAY['Battle of Bulge', 'Rolling hills', 'WWII history', 'Forests'], true),

-- Continue with remaining countries through UK...
-- North Macedonia, Montenegro, Netherlands, Norway (Lines 196-240)
('North Macedonia', NULL, 'Šar Mountains (Šar Planina)', 'Alpine peaks and lakes', ARRAY['Ljuboten', 'Popova Šapka', 'Alpine lakes', 'Traditional'], true),
('North Macedonia', NULL, 'Mavrovo National Park', 'Lake and mountain wilderness', ARRAY['Mavrovo Lake', 'Bistra', 'Radika canyon', 'Protected'], true),
('North Macedonia', NULL, 'Pelister National Park', 'Molika pine forests', ARRAY['Baba peak (2601m)', 'Mountain eyes lakes', 'Endemic flora', 'Unique'], true),
('North Macedonia', NULL, 'Galičica National Park', 'Between two famous lakes', ARRAY['Lake Ohrid', 'Lake Prespa', 'Diverse flora', 'UNESCO region'], true),
('Montenegro', NULL, 'Durmitor National Park', 'Glacial lakes and Europe''s deepest canyon', ARRAY['Black Lake', 'Bobotov Kuk (2523m)', 'Tara Canyon (1300m)', 'Rafting'], true),
('Montenegro', NULL, '18 Glacial Lakes (Durmitor)', 'Scattered pristine alpine lakes', ARRAY['Alpine environment', 'Pristine', 'Remote', 'Beautiful'], true),
('Montenegro', NULL, 'Prokletije National Park', 'Accursed Mountains shared region', ARRAY['Zla Kolata', 'Albanian border', 'Remote', 'Wild'], true),
('Montenegro', NULL, 'Lovćen National Park', 'Njegoš Mausoleum with panoramic views', ARRAY['Bay of Kotor', 'Serpentine roads', 'Cultural', 'Panoramic'], true),
('Montenegro', NULL, 'Biogradska Gora', 'Primeval forest with glacial lake', ARRAY['Biogradsko Lake', 'Old-growth trees', 'Pristine', 'Virgin forest'], true),
('Montenegro', NULL, 'Komovi Mountains', 'Remote massif with Via Dinarica sections', ARRAY['Via Dinarica', 'Remote', 'Alpine', 'Challenging'], true),
('Netherlands', NULL, 'Veluwe', 'Heathland national park', ARRAY['Posbank', 'Kammenroute', 'Hoge Veluwe', 'Flat', 'Heather'], true),
('Netherlands', NULL, 'Limburg Hills', 'Netherlands'' highest point', ARRAY['Vaalserberg (322m)', 'Three-country point', 'Rolling', 'Highest'], true),
('Netherlands', NULL, 'Wadden Islands', 'Coastal dunes and beaches', ARRAY['Texel', 'Terschelling', 'Cycling', 'Birdwatching', 'UNESCO'], true),
('Netherlands', NULL, 'Utrechtse Heuvelrug', 'Forested ridge with estates', ARRAY['Estates', 'Accessible', 'Utrecht', 'Forests'], true),
('Netherlands', NULL, 'Zuid-Limburg', 'Rolling hills with caves', ARRAY['Geuldal valley', 'Cave systems', 'Wine', 'Southern'], true)

ON CONFLICT (country, region, subregion) DO UPDATE SET
  description = EXCLUDED.description,
  key_features = EXCLUDED.key_features,
  is_active = EXCLUDED.is_active,
  updated_at = now();